export const DataTableActionTypes = {
    FETCH_DATA_START: 'FETCH_DATA_START',
    FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
    FETCH_DATA_FAIL: 'FETCH_DATA_FAIL',
    UPDATE_DATA: 'UPDATE_DATA',
    RESET_DATA: 'RESET_DATA',
    SAVE_TABLE_DATA: 'SAVE_TABLE_DATA',
}

export default DataTableActionTypes;